name: El Negocio del Deporte
favicon: null
layout_spectrum: 0.20911
typography_spectrum: 0.59253
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#46b0ce'
    - '#1d6d8c'
    - '#000000'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
